#!/bin/bash

set -e

# Workaround for https://www.postgresql.org/message-id/flat/7367.1375074342%40sss.pgh.pa.us
apt remove -y bison libbison-dev
wget http://launchpadlibrarian.net/140087283/libbison-dev_2.7.1.dfsg-1_amd64.deb
wget http://launchpadlibrarian.net/140087282/bison_2.7.1.dfsg-1_amd64.deb
dpkg -i libbison-dev_2.7.1.dfsg-1_amd64.deb bison_2.7.1.dfsg-1_amd64.deb
