#!/bin/bash

set -e

cd /home/postgres/src/postgres-pgbench
./configure >/tmp/pgbench-configure.log
cd src/bin/pgbench

make >/tmp/pgbench-make.log
cd /home/postgres
mkdir ref
cp -P src/postgres-pgbench/src/bin/pgbench/pgbench src/postgres-pgbench/src/interfaces/libpq/libpq.so* ref/
cat << 'EOF' > ref_pgbench
#!/bin/bash
export PGHOST="$(psql -Aqt  -c "SHOW unix_socket_directory")"
LD_LIBRARY_PATH=/home/postgres/ref /home/postgres/ref/pgbench "$@"
EOF
chmod a+x ref_pgbench
