#!/bin/bash

set -e

TIME=$1
[ -z "$TIME" ] && TIME=120

cp -r resources/htapbench htapbench
cd htapbench
grep 'javax.xml.bind' pom.xml || sed 's|\(</dependencies>\)|<dependency><groupId>javax.xml.bind</groupId><artifactId>jaxb-api</artifactId><version>2.3.1</version></dependency>\n\1|' -i pom.xml

mvn clean compile package
sed -e 's|<DBUrl>[^<]*</DBUrl>|<DBUrl>jdbc:postgresql://localhost:5432/htapb</DBUrl>|' \
 -e 's|<username>[^<]*</username>|<username>tester</username>|' \
 -e 's|<password>[^<]*</password>|<password>tester</password>|' \
 -e "s|<time>[^<]*</time>|<time>$TIME</time>|" \
 -i config/htapb_config_postgres.xml
createdb htapb
java -cp .:target/htapbench-0.95-jar-with-dependencies.jar pt.haslab.htapbench.core.HTAPBench -b htab -c config/htapb_config_postgres.xml --create true --load false --generateFiles false --filePath /tmp --execute false --calibrate false

java -cp .:target/htapbench-0.95-jar-with-dependencies.jar pt.haslab.htapbench.core.HTAPBench -b htapb -c config/htapb_config_postgres.xml --generateFiles true --filePath /tmp --execute false --calibrate true
ls -l /tmp/*.csv
echo "
COPY CUSTOMER FROM '/tmp/customer.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY DISTRICT FROM '/tmp/district.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY HISTORY FROM '/tmp/cust-hist.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY ITEM FROM '/tmp/item.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY NATION FROM '/tmp/nation.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY NEW_ORDER FROM '/tmp/new-order.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY OORDER FROM '/tmp/order.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY ORDER_LINE FROM '/tmp/order-line.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY REGION FROM '/tmp/region.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY STOCK FROM '/tmp/stock.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY SUPPLIER FROM '/tmp/supplier.csv' USING DELIMITERS ',' WITH NULL as 'null';
COPY WAREHOUSE FROM '/tmp/warehouse.csv' USING DELIMITERS ',' WITH NULL as 'null';
" | psql -d htapb
